import test from "node:test";
import assert from "node:assert/strict";
import { getAgentProvider, type AgentStreamEvent } from "../agents.js";

const ada = getAgentProvider("ada");
assert.ok(ada, "ada provider must be registered");

type ParserLine = (line: string) => AgentStreamEvent | AgentStreamEvent[] | null;
type ParserFactory = () => ParserLine;

function createParser(): ParserLine {
  assert.ok(ada, "ada provider must be registered");
  assert.ok(typeof ada.createParser === "function", "ada provider must expose createParser");
  const factory = ada.createParser as ParserFactory;
  return factory();
}

/**
 * Flatten the parser's per-line return into the sequence of normalized
 * events. A single line can produce an array (e.g. flush prose before a
 * tool call), and an empty array or `null` line contributes nothing.
 */
function runFixture(jsonl: string): AgentStreamEvent[] {
  const parse = createParser();
  const out: AgentStreamEvent[] = [];
  for (const rawLine of jsonl.split("\n")) {
    const line = rawLine.trim();
    if (!line) continue;
    const parsed = parse(line);
    if (parsed == null) continue;
    if (Array.isArray(parsed)) {
      for (const event of parsed) {
        if (event != null) out.push(event);
      }
    } else {
      out.push(parsed);
    }
  }
  return out;
}

test("ada parser: run.started resets state and emits a normalized event", () => {
  const events = runFixture(
    [
      JSON.stringify({
        type: "run.started",
        sessionId: "sess-1",
        model: "ada/test",
        workingDirectory: "/tmp/work",
        timestamp: "2026-06-08T00:00:00.000Z",
      }),
    ].join("\n")
  );

  assert.deepEqual(events, [
    {
      type: "run.started",
      sessionId: "sess-1",
      model: "ada/test",
      workingDirectory: "/tmp/work",
      timestamp: "2026-06-08T00:00:00.000Z",
    },
  ]);
});

test("ada parser: assistant.text.delta events accumulate and flush as a single assistant.text", () => {
  const events = runFixture(
    [
      JSON.stringify({
        type: "run.started",
        sessionId: "sess-2",
        model: "ada/test",
        workingDirectory: "/tmp/work",
        timestamp: "2026-06-08T00:00:00.000Z",
      }),
      JSON.stringify({ type: "assistant.text.delta", text: "I'll " }),
      JSON.stringify({ type: "assistant.text.delta", text: "implement " }),
      JSON.stringify({ type: "assistant.text.delta", text: "the fix." }),
      JSON.stringify({ type: "run.completed", sessionId: "sess-2", stopReason: "completed" }),
    ].join("\n")
  );

  assert.deepEqual(events, [
    {
      type: "run.started",
      sessionId: "sess-2",
      model: "ada/test",
      workingDirectory: "/tmp/work",
      timestamp: "2026-06-08T00:00:00.000Z",
    },
    // The accumulated text segment is emitted once, at the next
    // non-delta event. Three token deltas collapse into a single
    // `assistant.text` event.
    { type: "assistant.text", text: "I'll implement the fix." },
    {
      type: "run.completed",
      sessionId: "sess-2",
      status: "completed",
      stopReason: "completed",
      // generated by the parser when the input omitted timestamp
      timestamp: events[events.length - 1].type === "run.completed"
        ? (events[events.length - 1] as { timestamp: string }).timestamp
        : "",
    },
  ]);

  const completed = events[events.length - 1];
  assert.equal(completed.type, "run.completed");
});

test("ada parser: text and reasoning are emitted in the right order between tool calls", () => {
  const events = runFixture(
    [
      JSON.stringify({ type: "run.started", sessionId: "sess-3" }),
      JSON.stringify({ type: "assistant.reasoning.delta", text: "Thinking... " }),
      JSON.stringify({ type: "assistant.reasoning.delta", text: "Done." }),
      JSON.stringify({ type: "assistant.text.delta", text: "Hello " }),
      JSON.stringify({ type: "assistant.text.delta", text: "world." }),
      JSON.stringify({
        type: "tool.call",
        id: "call-1",
        name: "read_file",
        input: { path: "/tmp/foo" },
      }),
      JSON.stringify({ type: "tool.result", id: "call-1", content: "ok", isError: false }),
      JSON.stringify({ type: "assistant.text.delta", text: "Wrap up." }),
      JSON.stringify({ type: "run.completed", sessionId: "sess-3" }),
    ].join("\n")
  );

  const types = events.map((event) => event.type);
  assert.deepEqual(types, [
    "run.started",
    "assistant.reasoning", // reasoning flushed before text, both before the tool call
    "assistant.text",
    "tool.call",
    "tool.result",
    "assistant.text", // second text segment flushed at run completion
    "run.completed",
  ]);

  const reasoning = events.find((event) => event.type === "assistant.reasoning") as
    | { type: "assistant.reasoning"; text: string }
    | undefined;
  assert.ok(reasoning, "expected an assistant.reasoning event");
  assert.equal(reasoning.text, "Thinking... Done.");

  const texts = events.filter(
    (event): event is { type: "assistant.text"; text: string } =>
      event.type === "assistant.text"
  );
  assert.equal(texts.length, 2);
  assert.equal(texts[0].text, "Hello world.");
  assert.equal(texts[1].text, "Wrap up.");

  const toolCall = events.find((event) => event.type === "tool.call") as
    | { type: "tool.call"; id: string; name: string; input: Record<string, unknown> }
    | undefined;
  assert.ok(toolCall, "expected a tool.call event");
  assert.equal(toolCall.id, "call-1");
  assert.equal(toolCall.name, "read_file");
  assert.deepEqual(toolCall.input, { path: "/tmp/foo" });
});

test("ada parser: tool.call.delta accumulates inputDelta and tool.call can fall back to it", () => {
  // Ada streams the tool call as a sequence of `tool.call.delta`
  // events, then *omits* the structured `input` field on the final
  // `tool.call` event. The parser should rebuild the input by
  // concatenating the `inputDelta` JSON fragments and parsing them.
  const events = runFixture(
    [
      JSON.stringify({ type: "run.started", sessionId: "sess-4" }),
      JSON.stringify({
        type: "tool.call.delta",
        index: 0,
        id: "call-2",
        name: "run_command",
        inputDelta: '{"command":',
      }),
      JSON.stringify({
        type: "tool.call.delta",
        index: 0,
        inputDelta: '"ls ',
      }),
      JSON.stringify({
        type: "tool.call.delta",
        index: 0,
        inputDelta: '-la"}',
      }),
      JSON.stringify({
        type: "tool.call",
        id: "call-2",
        name: "run_command",
        input: {},
      }),
    ].join("\n")
  );

  const toolCall = events.find((event) => event.type === "tool.call") as
    | { type: "tool.call"; id: string; name: string; input: Record<string, unknown> }
    | undefined;
  assert.ok(toolCall, "expected a tool.call event");
  assert.equal(toolCall.id, "call-2");
  assert.equal(toolCall.name, "run_command");
  assert.deepEqual(toolCall.input, { command: "ls -la" });
});

test("ada parser: prefers the structured input on a final tool.call over the accumulated deltas", () => {
  // When the final `tool.call` already carries a complete `input`
  // object, the parser should not reach for the accumulated
  // `inputDelta` fragments. This guarantees the wire format can
  // change without silently breaking the structured-input path.
  const events = runFixture(
    [
      JSON.stringify({ type: "run.started", sessionId: "sess-5" }),
      JSON.stringify({
        type: "tool.call.delta",
        index: 0,
        inputDelta: '{"command":"should-not-be-used"}',
      }),
      JSON.stringify({
        type: "tool.call",
        id: "call-3",
        name: "run_command",
        input: { command: "echo hi" },
      }),
    ].join("\n")
  );

  const toolCall = events.find((event) => event.type === "tool.call") as
    | { type: "tool.call"; input: Record<string, unknown> }
    | undefined;
  assert.ok(toolCall, "expected a tool.call event");
  assert.deepEqual(toolCall.input, { command: "echo hi" });
});

test("ada parser: run.failed flushes any in-flight text before emitting the failure", () => {
  const events = runFixture(
    [
      JSON.stringify({ type: "run.started", sessionId: "sess-6" }),
      JSON.stringify({ type: "assistant.text.delta", text: "Half a " }),
      JSON.stringify({ type: "assistant.text.delta", text: "sentence." }),
      JSON.stringify({
        type: "run.failed",
        sessionId: "sess-6",
        error: "Provider error",
      }),
    ].join("\n")
  );

  const types = events.map((event) => event.type);
  assert.deepEqual(types, [
    "run.started",
    "assistant.text",
    "run.failed",
  ]);

  const text = events.find((event) => event.type === "assistant.text") as
    | { type: "assistant.text"; text: string }
    | undefined;
  assert.ok(text, "expected an assistant.text event before run.failed");
  assert.equal(text.text, "Half a sentence.");

  const failed = events.find((event) => event.type === "run.failed") as
    | { type: "run.failed"; error: string; sessionId: string }
    | undefined;
  assert.ok(failed, "expected a run.failed event");
  assert.equal(failed.error, "Provider error");
  assert.equal(failed.sessionId, "sess-6");
});

test("ada parser: a fresh run.started clears any in-flight segment from a prior run", () => {
  // Without a state reset, stale text accumulated by a previous run
  // would leak into the new turn. The parser should start each new
  // run from a clean slate.
  const events = runFixture(
    [
      JSON.stringify({ type: "run.started", sessionId: "sess-7" }),
      JSON.stringify({ type: "assistant.text.delta", text: "from the previous run" }),
      JSON.stringify({ type: "run.completed", sessionId: "sess-7" }),
      JSON.stringify({ type: "run.started", sessionId: "sess-8" }),
      JSON.stringify({ type: "assistant.text.delta", text: "fresh turn" }),
      JSON.stringify({ type: "run.completed", sessionId: "sess-8" }),
    ].join("\n")
  );

  const assistantTexts = events.filter(
    (event): event is { type: "assistant.text"; text: string } =>
      event.type === "assistant.text"
  );
  assert.equal(assistantTexts.length, 2);
  assert.equal(assistantTexts[0].text, "from the previous run");
  assert.equal(assistantTexts[1].text, "fresh turn");
});

test("ada parser: unknown event types are dropped, never forwarded as AgentStreamEvent", () => {
  // Regression guard for the original bug: the parser used to
  // blindly cast every JSONL line into `AgentStreamEvent`, which
  // let Ada's `assistant.text.delta` shape leak into the SSE
  // stream. The new parser must drop anything it doesn't
  // recognize.
  const events = runFixture(
    [
      JSON.stringify({ type: "run.started", sessionId: "sess-9" }),
      JSON.stringify({ type: "future.ada.event", payload: { foo: "bar" } }),
      JSON.stringify({ type: "run.completed", sessionId: "sess-9" }),
    ].join("\n")
  );

  const types = events.map((event) => event.type);
  assert.deepEqual(types, ["run.started", "run.completed"]);
  for (const event of events) {
    assert.ok(
      [
        "run.started",
        "assistant.text",
        "assistant.reasoning",
        "tool.call",
        "tool.result",
        "plan.updated",
        "plan.delta",
        "user.input_requested",
        "thread.status",
        "run.completed",
        "run.failed",
      ].includes(event.type),
      `event type ${event.type} is not a normalized AgentStreamEvent`
    );
  }
});
