import test from "node:test";
import assert from "node:assert/strict";
import { getAgentProvider, type AgentStreamEvent } from "../agents.js";

const anita = getAgentProvider("anita");
assert.ok(anita, "anita provider must be registered");

type ParserLine = (line: string) => AgentStreamEvent | AgentStreamEvent[] | null;
type ParserFactory = (autoApprove?: boolean) => ParserLine;

function createParser(autoApprove?: boolean): ParserLine {
  assert.ok(anita, "anita provider must be registered");
  assert.ok(typeof anita.createParser === "function", "anita provider must expose createParser");
  const factory = anita.createParser as ParserFactory;
  return factory(autoApprove);
}

/**
 * Flatten the parser's per-line return into the sequence of normalized
 * events. A single line can produce an array (e.g. flush prose before a
 * tool call), and an empty array or `null` line contributes nothing.
 */
function runFixture(jsonl: string, autoApprove?: boolean): AgentStreamEvent[] {
  const parse = createParser(autoApprove);
  const out: AgentStreamEvent[] = [];
  for (const rawLine of jsonl.split("\n")) {
    const line = rawLine.trim();
    if (!line) continue;
    const parsed = parse(line);
    if (parsed == null) continue;
    if (Array.isArray(parsed)) {
      for (const event of parsed) {
        if (event != null) out.push(event);
      }
    } else {
      out.push(parsed);
    }
  }
  return out;
}

test("anita parser: run.started resets state and emits a normalized event", () => {
  const events = runFixture(
    [
      JSON.stringify({
        type: "run.started",
        sessionId: "sess-1",
        model: "anita/test",
        workingDirectory: "/tmp/work",
        timestamp: "2026-06-08T00:00:00.000Z",
      }),
    ].join("\n")
  );

  assert.deepEqual(events, [
    {
      type: "run.started",
      sessionId: "sess-1",
      model: "anita/test",
      workingDirectory: "/tmp/work",
      timestamp: "2026-06-08T00:00:00.000Z",
    },
  ]);
});

test("anita parser: assistant.text.delta events accumulate and flush as a single assistant.text", () => {
  const events = runFixture(
    [
      JSON.stringify({
        type: "run.started",
        sessionId: "sess-2",
        model: "anita/test",
        workingDirectory: "/tmp/work",
        timestamp: "2026-06-08T00:00:00.000Z",
      }),
      JSON.stringify({ type: "assistant.text.delta", text: "I'll " }),
      JSON.stringify({ type: "assistant.text.delta", text: "implement " }),
      JSON.stringify({ type: "assistant.text.delta", text: "the fix." }),
      JSON.stringify({ type: "run.completed", sessionId: "sess-2", stopReason: "completed" }),
    ].join("\n")
  );

  assert.deepEqual(events, [
    {
      type: "run.started",
      sessionId: "sess-2",
      model: "anita/test",
      workingDirectory: "/tmp/work",
      timestamp: "2026-06-08T00:00:00.000Z",
    },
    // The accumulated text segment is emitted once, at the next
    // non-delta event. Three token deltas collapse into a single
    // `assistant.text` event.
    { type: "assistant.text", text: "I'll implement the fix." },
    {
      type: "run.completed",
      sessionId: "sess-2",
      status: "completed",
      stopReason: "completed",
      // generated by the parser when the input omitted timestamp
      timestamp: events[events.length - 1].type === "run.completed"
        ? (events[events.length - 1] as { timestamp: string }).timestamp
        : "",
    },
  ]);

  const completed = events[events.length - 1];
  assert.equal(completed.type, "run.completed");
});

test("anita parser: text and reasoning are emitted in the right order between tool calls", () => {
  const events = runFixture(
    [
      JSON.stringify({ type: "run.started", sessionId: "sess-3" }),
      JSON.stringify({ type: "assistant.reasoning.delta", text: "Thinking... " }),
      JSON.stringify({ type: "assistant.reasoning.delta", text: "Done." }),
      JSON.stringify({ type: "assistant.text.delta", text: "Hello " }),
      JSON.stringify({ type: "assistant.text.delta", text: "world." }),
      JSON.stringify({
        type: "tool.call",
        id: "call-1",
        name: "read_file",
        input: { path: "/tmp/foo" },
      }),
      JSON.stringify({ type: "tool.result", id: "call-1", content: "ok", isError: false }),
      JSON.stringify({ type: "assistant.text.delta", text: "Wrap up." }),
      JSON.stringify({ type: "run.completed", sessionId: "sess-3" }),
    ].join("\n")
  );

  const types = events.map((event) => event.type);
  assert.deepEqual(types, [
    "run.started",
    "assistant.reasoning", // reasoning flushed before text, both before the tool call
    "assistant.text",
    "tool.call",
    "tool.result",
    "assistant.text", // second text segment flushed at run completion
    "run.completed",
  ]);

  const reasoning = events.find((event) => event.type === "assistant.reasoning") as
    | { type: "assistant.reasoning"; text: string }
    | undefined;
  assert.ok(reasoning, "expected an assistant.reasoning event");
  assert.equal(reasoning.text, "Thinking... Done.");

  const texts = events.filter(
    (event): event is { type: "assistant.text"; text: string } =>
      event.type === "assistant.text"
  );
  assert.equal(texts.length, 2);
  assert.equal(texts[0].text, "Hello world.");
  assert.equal(texts[1].text, "Wrap up.");

  const toolCall = events.find((event) => event.type === "tool.call") as
    | { type: "tool.call"; id: string; name: string; input: Record<string, unknown> }
    | undefined;
  assert.ok(toolCall, "expected a tool.call event");
  assert.equal(toolCall.id, "call-1");
  assert.equal(toolCall.name, "read_file");
  assert.deepEqual(toolCall.input, { path: "/tmp/foo" });
});

test("anita parser: tool.call.delta accumulates inputDelta and tool.call can fall back to it", () => {
  // Anita streams the tool call as a sequence of `tool.call.delta`
  // events, then *omits* the structured `input` field on the final
  // `tool.call` event. The parser should rebuild the input by
  // concatenating the `inputDelta` JSON fragments and parsing them.
  const events = runFixture(
    [
      JSON.stringify({ type: "run.started", sessionId: "sess-4" }),
      JSON.stringify({
        type: "tool.call.delta",
        index: 0,
        id: "call-2",
        name: "run_command",
        inputDelta: '{"command":',
      }),
      JSON.stringify({
        type: "tool.call.delta",
        index: 0,
        inputDelta: '"ls ',
      }),
      JSON.stringify({
        type: "tool.call.delta",
        index: 0,
        inputDelta: '-la"}',
      }),
      JSON.stringify({
        type: "tool.call",
        id: "call-2",
        name: "run_command",
        input: {},
      }),
    ].join("\n")
  );

  const toolCall = events.find((event) => event.type === "tool.call") as
    | { type: "tool.call"; id: string; name: string; input: Record<string, unknown> }
    | undefined;
  assert.ok(toolCall, "expected a tool.call event");
  assert.equal(toolCall.id, "call-2");
  assert.equal(toolCall.name, "run_command");
  assert.deepEqual(toolCall.input, { command: "ls -la" });
});

test("anita parser: prefers the structured input on a final tool.call over the accumulated deltas", () => {
  // When the final `tool.call` already carries a complete `input`
  // object, the parser should not reach for the accumulated
  // `inputDelta` fragments. This guarantees the wire format can
  // change without silently breaking the structured-input path.
  const events = runFixture(
    [
      JSON.stringify({ type: "run.started", sessionId: "sess-5" }),
      JSON.stringify({
        type: "tool.call.delta",
        index: 0,
        inputDelta: '{"command":"should-not-be-used"}',
      }),
      JSON.stringify({
        type: "tool.call",
        id: "call-3",
        name: "run_command",
        input: { command: "echo hi" },
      }),
    ].join("\n")
  );

  const toolCall = events.find((event) => event.type === "tool.call") as
    | { type: "tool.call"; input: Record<string, unknown> }
    | undefined;
  assert.ok(toolCall, "expected a tool.call event");
  assert.deepEqual(toolCall.input, { command: "echo hi" });
});

test("anita parser: run.failed flushes any in-flight text before emitting the failure", () => {
  const events = runFixture(
    [
      JSON.stringify({ type: "run.started", sessionId: "sess-6" }),
      JSON.stringify({ type: "assistant.text.delta", text: "Half a " }),
      JSON.stringify({ type: "assistant.text.delta", text: "sentence." }),
      JSON.stringify({
        type: "run.failed",
        sessionId: "sess-6",
        error: "Provider error",
      }),
    ].join("\n")
  );

  const types = events.map((event) => event.type);
  assert.deepEqual(types, [
    "run.started",
    "assistant.text",
    "run.failed",
  ]);

  const text = events.find((event) => event.type === "assistant.text") as
    | { type: "assistant.text"; text: string }
    | undefined;
  assert.ok(text, "expected an assistant.text event before run.failed");
  assert.equal(text.text, "Half a sentence.");

  const failed = events.find((event) => event.type === "run.failed") as
    | { type: "run.failed"; error: string; sessionId: string }
    | undefined;
  assert.ok(failed, "expected a run.failed event");
  assert.equal(failed.error, "Provider error");
  assert.equal(failed.sessionId, "sess-6");
});

test("anita parser: run.cancelled flushes in-flight text and emits a normalized terminal event", () => {
  // Clean-cancellation path: Anita SIGINTs the run cooperatively and
  // emits `run.cancelled` before exiting with code 130 (see
  // coding-agent#66). The orchestrator must surface this as a
  // `run.cancelled` event (not drop it as an unknown type, and not
  // synthesize a `run.failed`) so the UI can show a soft "Run
  // cancelled" indicator instead of a red error banner.
  const events = runFixture(
    [
      JSON.stringify({ type: "run.started", sessionId: "sess-cancel-1" }),
      JSON.stringify({ type: "assistant.text.delta", text: "I was about to " }),
      JSON.stringify({ type: "assistant.text.delta", text: "finish." }),
      JSON.stringify({
        type: "run.cancelled",
        sessionId: "sess-cancel-1",
        reason: "user_interrupt",
        timestamp: "2026-06-10T00:00:00.000Z",
      }),
    ].join("\n")
  );

  const types = events.map((event) => event.type);
  assert.deepEqual(types, [
    "run.started",
    "assistant.text",
    "run.cancelled",
  ]);

  const text = events.find((event) => event.type === "assistant.text") as
    | { type: "assistant.text"; text: string }
    | undefined;
  assert.ok(text, "expected an assistant.text event before run.cancelled");
  assert.equal(text.text, "I was about to finish.");

  const cancelled = events.find((event) => event.type === "run.cancelled") as
    | {
        type: "run.cancelled";
        sessionId: string;
        reason: string;
        timestamp: string;
      }
    | undefined;
  assert.ok(cancelled, "expected a run.cancelled event");
  assert.equal(cancelled.sessionId, "sess-cancel-1");
  assert.equal(cancelled.reason, "user_interrupt");
  assert.equal(cancelled.timestamp, "2026-06-10T00:00:00.000Z");
});

test("anita parser: run.cancelled defaults reason to user_interrupt when omitted", () => {
  // The orchestrator should still get a usable `reason` when Anita
  // emits `run.cancelled` without one (older versions, partial
  // payloads, etc.). "user_interrupt" is the only reason Anita emits
  // today, so it's a safe default.
  const events = runFixture(
    [
      JSON.stringify({ type: "run.started", sessionId: "sess-cancel-2" }),
      JSON.stringify({
        type: "run.cancelled",
        sessionId: "sess-cancel-2",
      }),
    ].join("\n")
  );

  const cancelled = events.find((event) => event.type === "run.cancelled") as
    | { type: "run.cancelled"; reason: string; timestamp: string }
    | undefined;
  assert.ok(cancelled, "expected a run.cancelled event");
  assert.equal(cancelled.reason, "user_interrupt");
  assert.ok(
    typeof cancelled.timestamp === "string" && cancelled.timestamp.length > 0,
    "expected a generated timestamp when Anita omits one"
  );
});

test("anita parser: a fresh run.started clears any in-flight segment from a prior run", () => {
  // Without a state reset, stale text accumulated by a previous run
  // would leak into the new turn. The parser should start each new
  // run from a clean slate.
  const events = runFixture(
    [
      JSON.stringify({ type: "run.started", sessionId: "sess-7" }),
      JSON.stringify({ type: "assistant.text.delta", text: "from the previous run" }),
      JSON.stringify({ type: "run.completed", sessionId: "sess-7" }),
      JSON.stringify({ type: "run.started", sessionId: "sess-8" }),
      JSON.stringify({ type: "assistant.text.delta", text: "fresh turn" }),
      JSON.stringify({ type: "run.completed", sessionId: "sess-8" }),
    ].join("\n")
  );

  const assistantTexts = events.filter(
    (event): event is { type: "assistant.text"; text: string } =>
      event.type === "assistant.text"
  );
  assert.equal(assistantTexts.length, 2);
  assert.equal(assistantTexts[0].text, "from the previous run");
  assert.equal(assistantTexts[1].text, "fresh turn");
});

test("anita parser: unknown event types are dropped, never forwarded as AgentStreamEvent", () => {
  // Regression guard for the original bug: the parser used to
  // blindly cast every JSONL line into `AgentStreamEvent`, which
  // let Anita's `assistant.text.delta` shape leak into the SSE
  // stream. The new parser must drop anything it doesn't
  // recognize.
  const events = runFixture(
    [
      JSON.stringify({ type: "run.started", sessionId: "sess-9" }),
      JSON.stringify({ type: "future.anita.event", payload: { foo: "bar" } }),
      JSON.stringify({ type: "run.completed", sessionId: "sess-9" }),
    ].join("\n")
  );

  const types = events.map((event) => event.type);
  assert.deepEqual(types, ["run.started", "run.completed"]);
  for (const event of events) {
    assert.ok(
      [
        "run.started",
        "assistant.text",
        "assistant.reasoning",
        "tool.call",
        "tool.result",
        "plan.updated",
        "plan.delta",
        "user.input_requested",
        "thread.status",
        "run.completed",
        "run.failed",
        "run.cancelled",
      ].includes(event.type),
      `event type ${event.type} is not a normalized AgentStreamEvent`
    );
  }
});

test("anita parser: consumes accumulated tool.call.delta fragments when a later tool reuses the same index", () => {
  // Regression guard: a `tool.call` that arrives with a structured
  // `input` was leaving the accumulated `inputDelta` fragments in
  // the parser state. If a subsequent tool call reused the same
  // `index` and *did* need the fallback, the stale fragments would
  // be parsed as that new call's input. Worse, if the new call also
  // emitted `tool.call.delta` fragments for the same `index`, the
  // new fragments would be concatenated onto the stale ones,
  // producing a corrupt JSON string.
  const events = runFixture(
    [
      JSON.stringify({ type: "run.started", sessionId: "sess-10" }),
      // First call at index 0: emits deltas AND arrives with a
      // structured `input`. The parser should pick the structured
      // one and *drop the fragments*.
      JSON.stringify({
        type: "tool.call.delta",
        index: 0,
        inputDelta: '{"command":"STALE"}',
      }),
      JSON.stringify({
        type: "tool.call",
        id: "call-A",
        name: "run_command",
        index: 0,
        input: { command: "echo hello" },
      }),
      // Second call at the same index 0: emits deltas with no
      // structured `input` on the final event. Without the cleanup
      // the parser would see `{"command":"STALE"}{"command":"ls"}`
      // — invalid JSON — and fall through to an empty `input`,
      // hiding the tool arguments from the UI.
      JSON.stringify({
        type: "tool.call.delta",
        index: 0,
        inputDelta: '{"command":',
      }),
      JSON.stringify({
        type: "tool.call.delta",
        index: 0,
        inputDelta: '"ls"}',
      }),
      JSON.stringify({
        type: "tool.call",
        id: "call-B",
        name: "run_command",
        index: 0,
        input: {},
      }),
    ].join("\n")
  );

  const toolCalls = events.filter(
    (event): event is {
      type: "tool.call";
      id: string;
      name: string;
      input: Record<string, unknown>;
    } => event.type === "tool.call"
  );
  assert.equal(toolCalls.length, 2, "expected two normalized tool.call events");

  // First call: structured input wins.
  assert.equal(toolCalls[0].id, "call-A");
  assert.deepEqual(toolCalls[0].input, { command: "echo hello" });

  // Second call: fragments are *only* the new deltas. The stale
  // '{"command":"STALE"}' from the first call must not leak in.
  assert.equal(toolCalls[1].id, "call-B");
  assert.deepEqual(toolCalls[1].input, { command: "ls" });
});

test("anita parser: empty final tool.call with no prior deltas leaves input empty, not the previous call's", () => {
  // Companion regression guard: a `tool.call` with no `input` and
  // no prior `tool.call.delta` should yield an empty `input`
  // object, not silently inherit the previous call's accumulated
  // fragments.
  const events = runFixture(
    [
      JSON.stringify({ type: "run.started", sessionId: "sess-11" }),
      JSON.stringify({
        type: "tool.call.delta",
        index: 0,
        inputDelta: '{"command":"first"}',
      }),
      JSON.stringify({
        type: "tool.call",
        id: "call-1",
        name: "run_command",
        index: 0,
        input: { command: "first" },
      }),
      // No more deltas for the next call. The structured `input`
      // is empty, and the fragment map must also be empty (the
      // previous call was already consumed).
      JSON.stringify({
        type: "tool.call",
        id: "call-2",
        name: "run_command",
        index: 0,
        input: {},
      }),
    ].join("\n")
  );

  const toolCalls = events.filter(
    (event): event is {
      type: "tool.call";
      id: string;
      name: string;
      input: Record<string, unknown>;
    } => event.type === "tool.call"
  );
  assert.equal(toolCalls.length, 2);
  assert.deepEqual(toolCalls[0].input, { command: "first" });
  assert.deepEqual(toolCalls[1].input, {}, "input must be empty, not inherited");
});

test("anita parser: approval.request maps to tool.approval_requested when auto-approve is off", () => {
  const events = runFixture(
    [
      JSON.stringify({
        type: "approval.request",
        id: "call-9",
        tool: "run_command",
        input: { command: "rm -rf build" },
        timestamp: "2026-06-08T00:00:00.000Z",
      }),
    ].join("\n"),
    false
  );

  assert.deepEqual(events, [
    {
      type: "tool.approval_requested",
      id: "call-9",
      toolUseId: "call-9",
      toolName: "run_command",
      input: { command: "rm -rf build" },
      suggestions: [],
    },
  ]);
});

test("anita parser: approval events are dropped when auto-approve is on (audit-only)", () => {
  const events = runFixture(
    [
      JSON.stringify({ type: "approval.request", id: "c1", tool: "edit", input: {}, timestamp: "t" }),
      JSON.stringify({
        type: "approval.resolved",
        id: "c1",
        approved: true,
        reason: "user",
        timestamp: "t",
      }),
    ].join("\n"),
    true
  );

  assert.deepEqual(events, [], "auto-approve on must not surface approval cards");
});

test("anita parser: approval.resolved with reason 'user' is dropped (the POST already settled it)", () => {
  const events = runFixture(
    [
      JSON.stringify({ type: "approval.request", id: "c2", tool: "edit", input: {}, timestamp: "t" }),
      JSON.stringify({
        type: "approval.resolved",
        id: "c2",
        approved: true,
        reason: "user",
        timestamp: "t",
      }),
    ].join("\n"),
    false
  );

  assert.deepEqual(
    events,
    [
      {
        type: "tool.approval_requested",
        id: "c2",
        toolUseId: "c2",
        toolName: "edit",
        input: {},
        suggestions: [],
      },
    ],
    "only the request should surface; the user resolution is the POST's echo"
  );
});

test("anita parser: non-user approval.resolved surfaces as tool.approval_resolved", () => {
  for (const reason of ["eof", "aborted", "error"] as const) {
    const events = runFixture(
      [
        JSON.stringify({
          type: "approval.resolved",
          id: "c3",
          approved: false,
          reason,
          timestamp: "t",
        }),
      ].join("\n"),
      false
    );

    assert.deepEqual(events, [
      { type: "tool.approval_resolved", id: "c3", approved: false, reason },
    ]);
  }
});
