#!/bin/bash
set -e

# Dev defaults are offset (+2) from the packaged app's canonical ports
# (4500 client / 3100 API) so `npm run dev` next to a packaged Controller
# doesn't collide. Worktree PORT_OFFSET still adds on top.
CLIENT_BASE_PORT="${CLIENT_BASE_PORT:-4502}"
API_BASE_PORT="${API_BASE_PORT:-3102}"
OFFSET="${PORT_OFFSET:-0}"

if ! [[ "$CLIENT_BASE_PORT" =~ ^[0-9]+$ ]]; then
  echo "CLIENT_BASE_PORT must be a number" >&2
  exit 1
fi

if ! [[ "$API_BASE_PORT" =~ ^[0-9]+$ ]]; then
  echo "API_BASE_PORT must be a number" >&2
  exit 1
fi

if ! [[ "$OFFSET" =~ ^[0-9]+$ ]]; then
  echo "PORT_OFFSET must be a number" >&2
  exit 1
fi

CLIENT_PORT=$((CLIENT_BASE_PORT + OFFSET))
API_PORT=$((API_BASE_PORT + OFFSET))

cat > .env.local <<EOF
# Generated by .coding-orchestrator/setup.sh for this worktree.
PORT=$API_PORT
API_PORT=$API_PORT
VITE_API_PORT=$API_PORT
VITE_DEV_SERVER_PORT=$CLIENT_PORT
EOF

npm install
